os:
  - osx
language: swift
osx_image: xcode12.2
env:
  - PROJECT_NAME=lab_1
script:
  - xcodebuild build-for-testing -workspace SomeNews.xcworkspace -scheme SomeNews -sdk iphonesimulator -destination id=35E5C21F-F1BE-4CFA-B056-0A1FAAE10BFC
  - xcodebuild test -workspace SomeNews.xcworkspace -scheme SomeNews -sdk iphonesimulator -destination id=35E5C21F-F1BE-4CFA-B056-0A1FAAE10BFC
